<a href="https://colab.research.google.com/github/Meet200/Machine_Learning-/blob/main/decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [225]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math


In [226]:
from google.colab import drive

In [227]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [228]:
cd /content/drive/"My Drive/Colab Notebooks/Linear regression"

/content/drive/My Drive/Colab Notebooks/Linear regression


In [229]:
features = pd.read_csv("temps.csv")
print(features)


     year  month  day  ... forecast_acc  forecast_under  friend
0    2016      1    1  ...           50              44      29
1    2016      1    2  ...           50              44      61
2    2016      1    3  ...           46              47      56
3    2016      1    4  ...           48              46      53
4    2016      1    5  ...           46              46      41
..    ...    ...  ...  ...          ...             ...     ...
343  2016     12   27  ...           50              47      47
344  2016     12   28  ...           49              44      58
345  2016     12   29  ...           50              45      65
346  2016     12   30  ...           46              44      42
347  2016     12   31  ...           48              47      57

[348 rows x 12 columns]


In [230]:
features = pd.get_dummies(features)
features

year  month  day  temp_2  ...  week_Sun  week_Thurs  week_Tues  week_Wed
0    2016      1    1      45  ...         0           0          0         0
1    2016      1    2      44  ...         0           0          0         0
2    2016      1    3      45  ...         1           0          0         0
3    2016      1    4      44  ...         0           0          0         0
4    2016      1    5      41  ...         0           0          1         0
..    ...    ...  ...     ...  ...       ...         ...        ...       ...
343  2016     12   27      42  ...         0           0          1         0
344  2016     12   28      42  ...         0           0          0         1
345  2016     12   29      47  ...         0           1          0         0
346  2016     12   30      48  ...         0           0          0         0
347  2016     12   31      48  ...         0           0          0         0

[348 rows x 18 columns]

In [231]:
features.shape

(348, 18)

In [232]:
labels=np.array(features['actual'])
labels

array([45, 44, 41, 40, 44, 51, 45, 48, 50, 52, 45, 49, 55, 49, 48, 54, 50,
       54, 48, 52, 52, 57, 48, 51, 54, 56, 57, 56, 52, 48, 47, 46, 51, 49,
       49, 53, 49, 51, 57, 62, 56, 55, 58, 55, 56, 57, 53, 51, 53, 51, 51,
       60, 59, 61, 60, 57, 53, 58, 55, 59, 57, 64, 60, 53, 54, 55, 56, 55,
       52, 54, 49, 51, 53, 58, 63, 61, 55, 56, 57, 53, 54, 57, 59, 51, 56,
       64, 68, 73, 71, 63, 69, 60, 57, 68, 77, 76, 66, 59, 58, 60, 59, 59,
       60, 68, 77, 89, 81, 81, 73, 64, 65, 55, 59, 60, 61, 64, 61, 68, 77,
       87, 74, 60, 68, 77, 82, 63, 67, 75, 81, 77, 82, 65, 57, 60, 71, 64,
       63, 66, 59, 66, 65, 66, 66, 65, 64, 64, 64, 71, 79, 75, 71, 80, 81,
       92, 86, 85, 67, 65, 67, 65, 70, 66, 60, 67, 71, 67, 65, 70, 76, 73,
       75, 68, 69, 71, 78, 85, 79, 74, 73, 76, 76, 71, 68, 69, 76, 68, 74,
       71, 74, 74, 77, 75, 77, 76, 72, 80, 73, 78, 82, 81, 71, 75, 80, 85,
       79, 83, 85, 88, 76, 73, 77, 73, 75, 80, 79, 72, 72, 73, 72, 76, 80,
       87, 90, 83, 84, 81

In [233]:
features = features.drop('actual', axis=1)
features

year  month  day  temp_2  ...  week_Sun  week_Thurs  week_Tues  week_Wed
0    2016      1    1      45  ...         0           0          0         0
1    2016      1    2      44  ...         0           0          0         0
2    2016      1    3      45  ...         1           0          0         0
3    2016      1    4      44  ...         0           0          0         0
4    2016      1    5      41  ...         0           0          1         0
..    ...    ...  ...     ...  ...       ...         ...        ...       ...
343  2016     12   27      42  ...         0           0          1         0
344  2016     12   28      42  ...         0           0          0         1
345  2016     12   29      47  ...         0           1          0         0
346  2016     12   30      48  ...         0           0          0         0
347  2016     12   31      48  ...         0           0          0         0

[348 rows x 17 columns]

In [234]:
features_list = list(features.columns)
features=np.array(features)
features

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.016e+03, 1.000e+00, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.016e+03, 1.000e+00, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.016e+03, 1.200e+01, 2.900e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.016e+03, 1.200e+01, 3.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.016e+03, 1.200e+01, 3.100e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [235]:
from sklearn.model_selection import  train_test_split

In [236]:
train_feature,test_featuree,train_labels,test_labels=train_test_split(features,labels,test_size=0.25,random_state=42)

In [237]:
train_labels.shape

(261,)

In [238]:
from sklearn.ensemble import RandomForestRegressor

In [239]:
rf = RandomForestRegressor(n_estimators=500,random_state=42)

In [240]:
rf.fit(train_feature,train_labels)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=500, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [241]:
predictions = rf.predict(test_feature)
predictions

array([69.938, 61.472, 52.126, 61.508, 66.58 , 70.304, 78.388, 75.526,
       62.072, 74.168, 63.61 , 71.868, 38.42 , 62.198, 71.548, 56.102,
       60.984, 56.894, 56.714, 76.174, 63.932, 54.268, 66.364, 62.594,
       59.078, 53.12 , 67.014, 46.372, 61.93 , 80.246, 74.026, 64.376,
       55.218, 81.716, 74.146, 61.836, 53.682, 51.258, 69.194, 42.518,
       70.276, 57.146, 76.444, 42.294, 61.096, 73.568, 52.72 , 81.36 ,
       53.316, 42.612, 46.51 , 42.096, 64.124, 65.806, 74.266, 61.446,
       55.168, 59.82 , 54.726, 59.706, 65.516, 49.794, 60.91 , 70.222,
       60.12 , 59.058, 71.76 , 70.136, 76.838, 41.432, 76.878, 56.882,
       60.432, 50.44 , 54.516, 63.838, 43.81 , 74.48 , 47.476, 52.25 ,
       53.494, 67.748, 73.598, 72.71 , 63.402, 57.234, 46.15 ])

In [242]:
errors= abs(predictions-test_labels)
errors

array([ 3.938,  0.472,  0.126,  4.492,  3.42 , 11.696,  6.612,  8.474,
        2.928, 17.832,  2.61 , 13.132,  5.58 ,  2.802,  2.548,  5.898,
        3.016,  0.894,  3.714,  2.826,  0.932,  2.732,  0.636,  0.594,
        0.078,  2.88 ,  2.014,  5.628,  4.07 ,  4.246, 10.026,  3.376,
        7.218,  0.716,  2.854,  4.836,  4.318,  4.258,  1.194,  8.482,
        6.724,  1.146,  3.444,  8.706,  2.096, 13.432,  5.28 ,  0.36 ,
        4.684,  0.612,  2.49 ,  2.096,  0.876,  1.806,  4.266,  3.554,
        2.168,  2.82 ,  1.726,  0.294,  1.484,  0.794,  7.91 ,  1.222,
        5.12 ,  8.942,  4.24 ,  1.136,  1.162,  5.432,  2.878,  0.118,
        8.568,  0.44 ,  1.484,  3.162,  4.19 ,  5.52 ,  0.524,  3.25 ,
        3.506,  9.252,  7.402,  5.71 ,  2.598,  0.234,  1.15 ])

In [243]:
# Mean_absolute percentage error
mape=100*(errors/test_labels)
mean_error = np.mean(mape)

In [244]:
accuracy = 100-mean_error
accuracy 

93.88547981102626

In [245]:
from sklearn.tree import export_graphviz
import pydot

In [246]:
tree=rf.estimators_[5]
export_graphviz(tree,out_file='tree.dot',feature_names=features_list,rounded=True,precision=1)

In [247]:
(graph,)=pydot.graph_from_dot_file('tree.dot')
graph.write_png('tree.png');